remote_theme: "mmistakes/minimal-mistakes@4.12.2"

repository: e2nIEE/pandapower
title: "pandapower"
include:
  - _pages

defaults:
  - scope:
      path: "_pages"
    values:
      layout: single
      author_profile: false
     
author:
  name    : "pandapower"
#  avatar   : "/images/pp.svg"
  bio      : "An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation. "
  location : Kassel, Germany
  email    : info@pandapower.org
  github   : e2nIEE/pandapower
  
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
